### ISSUE TITLE
[Question]: When using Easegress as an Ingress controller, how can I add a global filter to the default HTTP server?

### ISSUE THREAD

**Issue by tjqc0512** [easegress-io/easegress#1240]
### This is not Bug report or Feature request

- [X] I confirm that this is not bug report or feature request.

### Is this question answered in [the documentation](https://github.com/megaease/easegress/blob/main/doc/README.md)?

- [X] I have searched the documentation

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Your question

When using Easegress as an Ingress controller, I want to add a global filter to the default HTTP server created by the Easegress Ingress controller, to ensure all traffic first passes through the global filter before being forwarded to the backend services. 
I have already configured a global filter for the HTTP server in the controller.yaml, but it does not take effect. All traffic is directly forwarded to the backend services without going through the global filter.
```
apiVersion: v1
data:
  easegress-server.yaml: |
    name: ingress-easegress
    cluster-name: easegress-ingress-controller
    cluster-role: primary
    api-addr: 0.0.0.0:2381
    data-dir: /opt/easegress/data
    log-dir: /opt/easegress/log
    debug: true
    log: info
  controller.yaml: |
    kind: IngressController
    name: easegress-ingress-controller
    namespaces:
    - ingress-easegress
    - gw-cscc
    - test
    ingressClass: easegress
    httpServer:
      globalFilter: global-filter
      port: 8080
      https: false
      keepAlive: true
      keepAliveTimeout: 60s
      maxConnections: 10240   
```
However, in a new HTTP server that I created within the Easegress ingress controller, the traffic can normally pass through the global filter. Is it because the default HTTP server created by the Easegress ingress controller does not support configuring global filters?
```
  pip.yaml: |
    kind: HTTPServer
    name: httpserver-test-rsa
    globalFilter: global-filter
    port: 8081
    rules:
      - paths:
        - pathPrefix: /service2
          backend: pipeline-demo
    ---    
    name: pipeline-demo
    kind: Pipeline
    flow:
      - filter: rsa
        jumpIf:
          invalid: END
      - filter: proxy         
    filters:
      - name: rsa
        kind: Validator 
        headers:
          Is-Valid:
            values: ["abc", "goodplan"] 
      - name: proxy
        kind: Proxy
        pools:
        - servers:
          - url: http://hello-service:60002
          loadBalance:
            policy: roundRobin
    ---
    name: global-filter
    kind: GlobalFilter
    beforePipeline:
      flow:
        - filter: rsaAuthFilter
      filters:
        - name: rsaAuthFilter
          kind: RsaAuthFilter   
```
