### ISSUE TITLE
The IP filter in HTTP Server rules works beyond its intended scope

### ISSUE THREAD

**Issue by llooper-dev** [easegress-io/easegress#205]
配置一，与配置二，只是ipFilter位置不一样，但是效果就有差别，理论上，ipFilter不是只作用在配置的rule里面吗。

kind: HTTPServer
name: facen-httpproxy
port: 10080
keepAlive: true
https: false
rules:
  - paths:
      - pathPrefix: /facen/v2/
        backend: facen-algapi-pipeline2
      - pathPrefix: /facen/v3/
        backend: facen-algapi-pipeline3
  - ipFilter:
      blockByDefault: true
      allowIPs:
        - 127.0.0.1
      blockIPs:
        - 192.168.9.45
    paths:
      - pathPrefix: /facen/api/
        backend: facen-algapi-pipeline
      - pathPrefix: /facen/v1/
        backend: facen-algapi-pipeline

  配置二：

kind: HTTPServer
name: facen-httpproxy
port: 10080
keepAlive: true
https: false
rules:
  - ipFilter:
      blockByDefault: true
      allowIPs:
        - 127.0.0.1
      blockIPs:
        - 192.168.9.45
    paths:
      - pathPrefix: /facen/api/
        backend: facen-algapi-pipeline
      - pathPrefix: /facen/v1/
        backend: facen-algapi-pipeline
 - paths:
      - pathPrefix: /facen/v2/
        backend: facen-algapi-pipeline2
      - pathPrefix: /facen/v3/
        backend: facen-algapi-pipeline3

**Comment by benja-wu** [comment]
Hi @llooper-dev
* First of all, I recommend writing the YAML configuration with the help of markdown format. I think the two configuration are 
``` yaml
kind: HTTPServer
name: facen-httpproxy
port: 10080
keepAlive: true
https: false
rules:
  - paths:
      - pathPrefix: /facen/v2/
        backend: facen-algapi-pipeline2
      - pathPrefix: /facen/v3/
        backend: facen-algapi-pipeline3
  - ipFilter:
      blockByDefault: true
      allowIPs:
        - 127.0.0.1
      blockIPs:
        - 192.168.9.45
    paths:
      - pathPrefix: /facen/api/
        backend: facen-algapi-pipeline
      - pathPrefix: /facen/v1/
        backend: facen-algapi-pipeline
        
```
and 

``` yaml
kind: HTTPServer
name: facen-httpproxy
port: 10080
keepAlive: true
https: false
rules:
  - ipFilter:
      blockByDefault: true
      allowIPs:
        - 127.0.0.1
      blockIPs:
        - 192.168.9.45
    paths:
      - pathPrefix: /facen/api/
        backend: facen-algapi-pipeline
      - pathPrefix: /facen/v1/
        backend: facen-algapi-pipeline
 - paths:
      - pathPrefix: /facen/v2/
        backend: facen-algapi-pipeline2
      - pathPrefix: /facen/v3/
        backend: facen-algapi-pipeline3		    
```
That's better for reading. :-)
* I would like to know the difference between these two rules. From my understandings, one rule is for the `/facen/api/` and `/face/v1/` with IP filter enabled, the other rule is for `/face/v2/` and `/face/v3/` path without IP filter. Can u share what exactly the difference is for us?
* Easegress' HTTPServer detects the path matching according to the sequence of the rules array. And the IPfilter in your configuration works for the `/facen/api/` and `/facen/v1/` rule, so I think the effect for IP blocking should be the same.
* In this Easegress, we prefer using English for issue discussion, bug reporting and so on, Thx.
