### ISSUE TITLE
Routing by http method results in "405 Method Not Allowed"

### ISSUE THREAD

**Issue by localvar** [easegress-io/easegress#400]
**Describe the bug**
Routing by HTTP method results in "405 Method Not Allowed"

**To Reproduce**
1. Config an HTTP server with routing rules like below:
```yaml
- paths:
    - pathPrefix: /hello/
      backend: hello-get
      methods: [GET]
    - pathPrefix: /hello/
      backend: hello-delete
      methods: [DELETE]
```
2. Send a request to the HTTP server with method `DELETE` and path `/hello/1`
3. Easegress response with `HTTP/1.1 405 Method Not Allowed`

**Expected behavior**
The request was forwarded to the backend service successfully.
