### ISSUE TITLE
MonitorMetrics report by http

### ISSUE THREAD

**Issue by zouyingjie** [easegress-io/easegress#525]
Now the monitoring metrics of easegress can be reported through Kafka. 
```yaml
- kafka:
    brokers:
    - 172.10.1.111:9092
    - 172.10.1.112:9092
    - 172.10.1.113:9092
    topic: metrics-topic
  kind: EaseMonitorMetrics
  name: EaseMonitorMetrics-default
```

Easegress and Kafka may be in different network environments, so they may need to report indicators through the public network. However, exposing Kafka to the public network is not a good practice, so it needs to be forwarded through an external gateway.

Therefore, easegress needs to support reporting data via HTTP and configuring HTTP basic and mTLS.
