### ISSUE TITLE
Easegress does not support server level (request URIs independent) filter mechanism

### ISSUE THREAD

**Issue by jthann** [easegress-io/easegress#726]
Currently，In Easegress we have global filter to handle business logic that all pipelines need. But using GlobalFilter means the request URI must match the path rule we configure like following:  if client access URI  ```/a/xxx``` or ```/b/xxx``` ,the GlobalFilter logic will execute， but if clients access other URIs that is not matched by rules like ```/c/xxx```.  The GlobalFilter logic will not execute and just return http 404. Because in Easegress GlobalFilter execute after URI matching successfully.
```yaml
kind: GlobalFilter
name: gf
beforePipeline:
  flow:
    - filter: f1
  filters:
    - name: f1
      kind: Filter1
---
kind: HTTPServer
name: https
port: 80
globalFilter: gf
rules:
  - paths:
      - pathPrefix: /a
        backend: pipelineA
      - pathPrefix: /b
        backend: pipelineB
---
#omit pipeline config for clarity
```
This is a problem in practical use，in many cases，we need to handle logic from request URIs which are not matched and don't expect just return http 404 status to these requests. For example in our SSOAuth global filter，we need to handle ```login logout sendToken...```, these URIs will never be proxied to backend pipeline. And also there are other unknown URIs we need to return custom result.

So I think Easegress should support this mechanism，let's just call it ServerFilter interface(Just for discussion)，this ServerFilter should execute before URIs rule matching and user can implement the interface to develop custom logic.

For clarify this feature rationality.  In addition to practical usage，let's see other gateways in industry how to handle this.  First in Java ecosystem，if using SpringMVC or SpringBoot or Spring Cloud  Netflix Zuul(Based on servlet)，we have ```javax.servlet.Filter``` which is Servlet specification interface，enhanced by Spring Framework providing ```org.springframework.web.filter.OncePerRequestFilter``` ，users can implement to handle. if using Spring Cloud Gateway (Spring WebFlux based on)， we have ```org.springframework.web.server.WebFilter```.  In APISIX it provides ```global_rules: plugins:``` config. All these filters or plugins are request URIs independent.

**Comment by suchen-sci** [comment]
Hi @jthann thanks for your issue, here is a naive way to solve this problem. We are open to the discussion of server level filter, but it may a little bit confused with the idea of GlobalFilter... 

Any idea here?
```
kind: GlobalFilter
name: gf
beforePipeline:
  flow:
    - filter: f1
  filters:
    - name: f1
      kind: Filter1
---
kind: HTTPServer
name: https
port: 80
globalFilter: gf
rules:
  - paths:
      - pathPrefix: /a
        backend: pipelineA
      - pathPrefix: /b
        backend: pipelineB
      - backend: pipelineNone
---
#omit pipeline config for clarity


kind: Pipeline
name: pipelineNone
flow: 
- filter: doNothing
  namespace: spacefornothing
filters:
- filter: doNothing
  kind: FilterDoNothing
```

**Comment by suchen-sci** [comment]
Hi @jthann we do some discuss about this issue, we plan to add a special built-in pipeline called `NopPipeline`. And this pipeline do nothing. So previous naive approach become following: 

```
kind: GlobalFilter
name: gf
beforePipeline:
  flow:
    - filter: f1
  filters:
    - name: f1
      kind: Filter1
---
kind: HTTPServer
name: https
port: 80
globalFilter: gf
rules:
  - paths:
      - pathPrefix: /a
        backend: pipelineA
      - pathPrefix: /b
        backend: pipelineB
      - backend: NopPipeline
---
#omit pipeline config for clarity
```
Add server level filter maybe not necessary since we already have GlobalFilter. Tell us if this is ok for you. Thanks again for your issue.
